//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalWebService.NotificionesWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WS.frutilla.pucp.edu.pe/", ConfigurationName="NotificionesWS.NotificacionWS")]
    public interface NotificacionWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.frutilla.pucp.edu.pe/NotificacionWS/listarTodosRequest", ReplyAction="http://WS.frutilla.pucp.edu.pe/NotificacionWS/listarTodosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LocalWebService.NotificionesWS.listarTodosResponse listarTodos(LocalWebService.NotificionesWS.listarTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.frutilla.pucp.edu.pe/NotificacionWS/listarTodosRequest", ReplyAction="http://WS.frutilla.pucp.edu.pe/NotificacionWS/listarTodosResponse")]
        System.Threading.Tasks.Task<LocalWebService.NotificionesWS.listarTodosResponse> listarTodosAsync(LocalWebService.NotificionesWS.listarTodosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.frutilla.pucp.edu.pe/NotificacionWS/listarPorClienteRequest", ReplyAction="http://WS.frutilla.pucp.edu.pe/NotificacionWS/listarPorClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LocalWebService.NotificionesWS.listarPorClienteResponse listarPorCliente(LocalWebService.NotificionesWS.listarPorClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.frutilla.pucp.edu.pe/NotificacionWS/listarPorClienteRequest", ReplyAction="http://WS.frutilla.pucp.edu.pe/NotificacionWS/listarPorClienteResponse")]
        System.Threading.Tasks.Task<LocalWebService.NotificionesWS.listarPorClienteResponse> listarPorClienteAsync(LocalWebService.NotificionesWS.listarPorClienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.frutilla.pucp.edu.pe/NotificacionWS/listarPorFechaRequest", ReplyAction="http://WS.frutilla.pucp.edu.pe/NotificacionWS/listarPorFechaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LocalWebService.NotificionesWS.listarPorFechaResponse listarPorFecha(LocalWebService.NotificionesWS.listarPorFechaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.frutilla.pucp.edu.pe/NotificacionWS/listarPorFechaRequest", ReplyAction="http://WS.frutilla.pucp.edu.pe/NotificacionWS/listarPorFechaResponse")]
        System.Threading.Tasks.Task<LocalWebService.NotificionesWS.listarPorFechaResponse> listarPorFechaAsync(LocalWebService.NotificionesWS.listarPorFechaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.frutilla.pucp.edu.pe/NotificacionWS/listarPorSupervisorRequest", ReplyAction="http://WS.frutilla.pucp.edu.pe/NotificacionWS/listarPorSupervisorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LocalWebService.NotificionesWS.listarPorSupervisorResponse listarPorSupervisor(LocalWebService.NotificionesWS.listarPorSupervisorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.frutilla.pucp.edu.pe/NotificacionWS/listarPorSupervisorRequest", ReplyAction="http://WS.frutilla.pucp.edu.pe/NotificacionWS/listarPorSupervisorResponse")]
        System.Threading.Tasks.Task<LocalWebService.NotificionesWS.listarPorSupervisorResponse> listarPorSupervisorAsync(LocalWebService.NotificionesWS.listarPorSupervisorRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WS.frutilla.pucp.edu.pe/")]
    public partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoProdField;
        
        private string descripcionField;
        
        private int idProductoField;
        
        private string nombreField;
        
        private double precioUnitarioField;
        
        private int stockField;
        
        private int stockMinimoField;
        
        private tipoEstado tipoEstadoField;
        
        private bool tipoEstadoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoProd {
            get {
                return this.codigoProdField;
            }
            set {
                this.codigoProdField = value;
                this.RaisePropertyChanged("codigoProd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double precioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                this.precioUnitarioField = value;
                this.RaisePropertyChanged("precioUnitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int stockMinimo {
            get {
                return this.stockMinimoField;
            }
            set {
                this.stockMinimoField = value;
                this.RaisePropertyChanged("stockMinimo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public tipoEstado tipoEstado {
            get {
                return this.tipoEstadoField;
            }
            set {
                this.tipoEstadoField = value;
                this.RaisePropertyChanged("tipoEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoEstadoSpecified {
            get {
                return this.tipoEstadoFieldSpecified;
            }
            set {
                this.tipoEstadoFieldSpecified = value;
                this.RaisePropertyChanged("tipoEstadoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WS.frutilla.pucp.edu.pe/")]
    public enum tipoEstado {
        
        /// <remarks/>
        DISPONIBLE,
        
        /// <remarks/>
        AGOTADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WS.frutilla.pucp.edu.pe/")]
    public partial class notificacionDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private string fechaStrField;
        
        private int idClienteField;
        
        private int idNotificacionField;
        
        private int idSupervisorField;
        
        private ushort tipoReceptorField;
        
        private string tituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fechaStr {
            get {
                return this.fechaStrField;
            }
            set {
                this.fechaStrField = value;
                this.RaisePropertyChanged("fechaStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idNotificacion {
            get {
                return this.idNotificacionField;
            }
            set {
                this.idNotificacionField = value;
                this.RaisePropertyChanged("idNotificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idSupervisor {
            get {
                return this.idSupervisorField;
            }
            set {
                this.idSupervisorField = value;
                this.RaisePropertyChanged("idSupervisor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public ushort tipoReceptor {
            get {
                return this.tipoReceptorField;
            }
            set {
                this.tipoReceptorField = value;
                this.RaisePropertyChanged("tipoReceptor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodos", WrapperNamespace="http://WS.frutilla.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS.frutilla.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idLocal;
        
        public listarTodosRequest() {
        }
        
        public listarTodosRequest(int idLocal) {
            this.idLocal = idLocal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosResponse", WrapperNamespace="http://WS.frutilla.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS.frutilla.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LocalWebService.NotificionesWS.producto[] @return;
        
        public listarTodosResponse() {
        }
        
        public listarTodosResponse(LocalWebService.NotificionesWS.producto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorCliente", WrapperNamespace="http://WS.frutilla.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS.frutilla.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public listarPorClienteRequest() {
        }
        
        public listarPorClienteRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorClienteResponse", WrapperNamespace="http://WS.frutilla.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS.frutilla.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LocalWebService.NotificionesWS.notificacionDTO[] @return;
        
        public listarPorClienteResponse() {
        }
        
        public listarPorClienteResponse(LocalWebService.NotificionesWS.notificacionDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorFecha", WrapperNamespace="http://WS.frutilla.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorFechaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS.frutilla.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS.frutilla.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public listarPorFechaRequest() {
        }
        
        public listarPorFechaRequest(string arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorFechaResponse", WrapperNamespace="http://WS.frutilla.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorFechaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS.frutilla.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LocalWebService.NotificionesWS.notificacionDTO[] @return;
        
        public listarPorFechaResponse() {
        }
        
        public listarPorFechaResponse(LocalWebService.NotificionesWS.notificacionDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorSupervisor", WrapperNamespace="http://WS.frutilla.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorSupervisorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS.frutilla.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public listarPorSupervisorRequest() {
        }
        
        public listarPorSupervisorRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorSupervisorResponse", WrapperNamespace="http://WS.frutilla.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorSupervisorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS.frutilla.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LocalWebService.NotificionesWS.notificacionDTO[] @return;
        
        public listarPorSupervisorResponse() {
        }
        
        public listarPorSupervisorResponse(LocalWebService.NotificionesWS.notificacionDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NotificacionWSChannel : LocalWebService.NotificionesWS.NotificacionWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificacionWSClient : System.ServiceModel.ClientBase<LocalWebService.NotificionesWS.NotificacionWS>, LocalWebService.NotificionesWS.NotificacionWS {
        
        public NotificacionWSClient() {
        }
        
        public NotificacionWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotificacionWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificacionWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificacionWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LocalWebService.NotificionesWS.listarTodosResponse LocalWebService.NotificionesWS.NotificacionWS.listarTodos(LocalWebService.NotificionesWS.listarTodosRequest request) {
            return base.Channel.listarTodos(request);
        }
        
        public LocalWebService.NotificionesWS.producto[] listarTodos(int idLocal) {
            LocalWebService.NotificionesWS.listarTodosRequest inValue = new LocalWebService.NotificionesWS.listarTodosRequest();
            inValue.idLocal = idLocal;
            LocalWebService.NotificionesWS.listarTodosResponse retVal = ((LocalWebService.NotificionesWS.NotificacionWS)(this)).listarTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LocalWebService.NotificionesWS.listarTodosResponse> LocalWebService.NotificionesWS.NotificacionWS.listarTodosAsync(LocalWebService.NotificionesWS.listarTodosRequest request) {
            return base.Channel.listarTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<LocalWebService.NotificionesWS.listarTodosResponse> listarTodosAsync(int idLocal) {
            LocalWebService.NotificionesWS.listarTodosRequest inValue = new LocalWebService.NotificionesWS.listarTodosRequest();
            inValue.idLocal = idLocal;
            return ((LocalWebService.NotificionesWS.NotificacionWS)(this)).listarTodosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LocalWebService.NotificionesWS.listarPorClienteResponse LocalWebService.NotificionesWS.NotificacionWS.listarPorCliente(LocalWebService.NotificionesWS.listarPorClienteRequest request) {
            return base.Channel.listarPorCliente(request);
        }
        
        public LocalWebService.NotificionesWS.notificacionDTO[] listarPorCliente(int arg0) {
            LocalWebService.NotificionesWS.listarPorClienteRequest inValue = new LocalWebService.NotificionesWS.listarPorClienteRequest();
            inValue.arg0 = arg0;
            LocalWebService.NotificionesWS.listarPorClienteResponse retVal = ((LocalWebService.NotificionesWS.NotificacionWS)(this)).listarPorCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LocalWebService.NotificionesWS.listarPorClienteResponse> LocalWebService.NotificionesWS.NotificacionWS.listarPorClienteAsync(LocalWebService.NotificionesWS.listarPorClienteRequest request) {
            return base.Channel.listarPorClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<LocalWebService.NotificionesWS.listarPorClienteResponse> listarPorClienteAsync(int arg0) {
            LocalWebService.NotificionesWS.listarPorClienteRequest inValue = new LocalWebService.NotificionesWS.listarPorClienteRequest();
            inValue.arg0 = arg0;
            return ((LocalWebService.NotificionesWS.NotificacionWS)(this)).listarPorClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LocalWebService.NotificionesWS.listarPorFechaResponse LocalWebService.NotificionesWS.NotificacionWS.listarPorFecha(LocalWebService.NotificionesWS.listarPorFechaRequest request) {
            return base.Channel.listarPorFecha(request);
        }
        
        public LocalWebService.NotificionesWS.notificacionDTO[] listarPorFecha(string arg0, int arg1) {
            LocalWebService.NotificionesWS.listarPorFechaRequest inValue = new LocalWebService.NotificionesWS.listarPorFechaRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            LocalWebService.NotificionesWS.listarPorFechaResponse retVal = ((LocalWebService.NotificionesWS.NotificacionWS)(this)).listarPorFecha(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LocalWebService.NotificionesWS.listarPorFechaResponse> LocalWebService.NotificionesWS.NotificacionWS.listarPorFechaAsync(LocalWebService.NotificionesWS.listarPorFechaRequest request) {
            return base.Channel.listarPorFechaAsync(request);
        }
        
        public System.Threading.Tasks.Task<LocalWebService.NotificionesWS.listarPorFechaResponse> listarPorFechaAsync(string arg0, int arg1) {
            LocalWebService.NotificionesWS.listarPorFechaRequest inValue = new LocalWebService.NotificionesWS.listarPorFechaRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((LocalWebService.NotificionesWS.NotificacionWS)(this)).listarPorFechaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LocalWebService.NotificionesWS.listarPorSupervisorResponse LocalWebService.NotificionesWS.NotificacionWS.listarPorSupervisor(LocalWebService.NotificionesWS.listarPorSupervisorRequest request) {
            return base.Channel.listarPorSupervisor(request);
        }
        
        public LocalWebService.NotificionesWS.notificacionDTO[] listarPorSupervisor(int arg0) {
            LocalWebService.NotificionesWS.listarPorSupervisorRequest inValue = new LocalWebService.NotificionesWS.listarPorSupervisorRequest();
            inValue.arg0 = arg0;
            LocalWebService.NotificionesWS.listarPorSupervisorResponse retVal = ((LocalWebService.NotificionesWS.NotificacionWS)(this)).listarPorSupervisor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LocalWebService.NotificionesWS.listarPorSupervisorResponse> LocalWebService.NotificionesWS.NotificacionWS.listarPorSupervisorAsync(LocalWebService.NotificionesWS.listarPorSupervisorRequest request) {
            return base.Channel.listarPorSupervisorAsync(request);
        }
        
        public System.Threading.Tasks.Task<LocalWebService.NotificionesWS.listarPorSupervisorResponse> listarPorSupervisorAsync(int arg0) {
            LocalWebService.NotificionesWS.listarPorSupervisorRequest inValue = new LocalWebService.NotificionesWS.listarPorSupervisorRequest();
            inValue.arg0 = arg0;
            return ((LocalWebService.NotificionesWS.NotificacionWS)(this)).listarPorSupervisorAsync(inValue);
        }
    }
}
